### ISSUE TITLE
Add error status and messaging

### ISSUE THREAD

**Issue by kleneway** [jacob-ai-bot/jacob#49]
When JACoB stops work on a task due to an error or retry timeout, we currently only see this information on the GitHub comment. We need to also display this information in the web portal to let the user know what went wrong and provide a link to the Issue or PR where JACoB stopped working. 

- [x] Update the core `Task` type to add an optional `statusMessage` value
- [x] Add a new `Task` event to the JACoB core engine when it encounters a blocking error or hits the retry limit
    - [x] Mark the `status` as `TaskStatus.ERROR`
    - [x] Add the error message to the `statusMessage` field
- [ ] Update the `getTasks` function in the `eventsRouter` to use the most recent task event from the database and add the status to the output (currently it's dynamically generated based on the GitHub issue status)
- [ ] Update the `status` section at the bottom of the `Workspace` component to prominently display the error message and a red error message in case of an error
- [ ] Add a red error icon to the Workspace tab for the task
- [ ] Update the `onAdd` subscription function in `Dashboard.tsx` 
   - [ ] Update the status to the current task status (currently it assumes the task is done)
   - [ ] Add a toast error notification if a new `Task` with an error shows up

**Comment by cpirich** [comment]
This commit generates the `TaskStatus.ERROR` events: https://github.com/jacob-ai-bot/jacob/commit/d0c4093e5b1f3ac4b78cca139e2cbac9ddae81ce

@kleneway: Note that the `TaskSubType` field is still incomplete. As a result, we may generate these after failure for a variety of other commands (pull request review, build, create story, etc.) - and the `subType` will probably be `TaskSubType.EDIT_FILES` - which isn't particularly correct - nor will this failure event correspond to a previous `TaskStatus.IN_PROGRESS` event since we don't generate those for many other commands (sub types) yet.
